suppressPackageStartupMessages(library(data.table));library(ggplot2)
O<-'outputs/air_pollution_cc/manuscript_reviewed_bw';dir.create(file.path(O,'figures'),showWarnings=FALSE)
G<-c(CVD='Cardiovascular',CBVD='Cerebrovascular',MI='Myocardial infarction',ANGINA='Angina (unconfirmed acute)',IS='Ischemic stroke',ICH='Intracerebral hemorrhage',SAH='Subarachnoid hemorrhage');P<-c(PM25='PM2.5',PM10='PM10',O3='O3')
cols<-c(PM25='#000000',PM10='#000000',O3='#000000')
theme_set(theme_bw(base_size=12)+theme(panel.grid.minor=element_blank(),strip.background=element_rect(fill='#F2F2F2'),legend.position='bottom',plot.title=element_text(size=14)))
saveplot<-function(p,n,w=9,h=6){ggsave(file.path(O,'figures',paste0(n,'.png')),p,width=w,height=h,dpi=300);ggsave(file.path(O,'figures',paste0(n,'.pdf')),p,width=w,height=h,device=pdf)}
readfamily<-function(file){rbindlist(lapply(c('two_group','five_outcomes'),function(f)fread(file.path('outputs/air_pollution_cc',f,file))),fill=TRUE)}
raw<-rbindlist(list(fread('outputs/air_pollution_cc/two_group/两类疾病关联与敏感性.csv'),fread('outputs/air_pollution_cc/five_outcomes/五类疾病关联与敏感性.csv')),fill=TRUE)
b<-raw[scenario=='all_registry_all_coordinates'&weather_config=='main'&window=='lag01'];b[,outcome:=factor(G[outcome_id],levels=rev(G))];b[,pollutant:=factor(pollutant,levels=names(P))]
p<-ggplot(b,aes(OR,outcome,color=pollutant,shape=pollutant))+geom_vline(xintercept=1,linetype=2,color='grey50')+geom_errorbar(aes(xmin=lower,xmax=upper),orientation='y',position=position_dodge(.65),width=.15)+geom_point(position=position_dodge(.65),size=2.5)+scale_color_manual(values=cols,labels=P)+scale_shape_manual(values=c(16,17,15),labels=P)+labs(x='OR per 10 ug/m3 increase in lag 0-1 exposure (95% CI)',y=NULL,color=NULL,shape=NULL)
saveplot(p,'Figure2_main_forest',9,5.5)
for(f in c('two_group','five_outcomes')){
 ids<-if(f=='two_group')c('CVD','CBVD') else c('MI','ANGINA','IS','ICH','SAH')
 lag<-fread(file.path('outputs/air_pollution_cc',f,'分布滞后逐日.csv'));lag[,outcome:=factor(G[outcome_id],levels=G[ids])];lag[,pol:=factor(P[as.character(pollutant)],levels=P)]
 p<-ggplot(lag,aes(lag,OR))+geom_hline(yintercept=1,linetype=2,color='grey50')+geom_ribbon(aes(ymin=lower,ymax=upper),fill='#D9D9D9')+geom_line(color='#000000')+facet_grid(outcome~pol,scales='free_y')+scale_x_continuous(breaks=c(0,2,4,7))+labs(x='Lag (days)',y='Lag-specific OR per 10 ug/m3 (95% CI)')
 saveplot(p,if(f=='two_group')'Figure3_distributed_lag' else 'FigureS3_subtype_distributed_lag',9,if(f=='two_group')5.5 else 10)
 cur<-fread(file.path('outputs/air_pollution_cc',f,'暴露反应曲线.csv'));cur[,outcome:=factor(G[outcome_id],levels=G[ids])];cur[,pol:=factor(P[as.character(pollutant)],levels=P)]
 p<-ggplot(cur,aes(concentration,OR))+geom_hline(yintercept=1,linetype=2,color='grey50')+geom_ribbon(aes(ymin=lower,ymax=upper),fill='#D9D9D9')+geom_line(color='#000000')+facet_grid(outcome~pol,scales='free')+labs(x='Lag 0-1 concentration (ug/m3)',y='OR relative to reference concentration (95% CI)')
 saveplot(p,if(f=='two_group')'Figure4_exposure_response' else 'FigureS4_subtype_exposure_response',9,if(f=='two_group')5.5 else 10)
 dual<-fread(file.path('outputs/air_pollution_cc',f,'双污染物模型.csv'));dual[,pollutant:=ifelse(term=='poll_first',first,second)];dual[,model:=paste0('Adjusted for ',ifelse(term=='poll_first',second,first))]
 single<-copy(b[outcome_id%in%ids]);single[,model:='Single pollutant'];dual<-rbindlist(list(dual,single),fill=TRUE);dual[,pol:=factor(P[as.character(pollutant)],levels=P)];dual[,outcome:=factor(G[outcome_id],levels=G[ids])];dual[,model:=factor(model,levels=c('Single pollutant','Adjusted for PM25','Adjusted for PM10','Adjusted for O3'))]
 p<-ggplot(dual,aes(OR,model))+geom_vline(xintercept=1,linetype=2,color='grey50')+geom_errorbar(aes(xmin=lower,xmax=upper),orientation='y',width=.15)+geom_point(color='#000000',size=2)+facet_grid(outcome~pol,scales='free_y')+labs(x='OR per 10 ug/m3 (95% CI)',y=NULL)
 saveplot(p,if(f=='two_group')'Figure5_two_pollutant' else 'FigureS5_subtype_two_pollutant',9,if(f=='two_group')5.8 else 10)
 ext<-fread(file.path(O,'tables','supp_reference_extensions.csv'));ll<-rbindlist(list(raw[outcome_id%in%ids&scenario=='all_registry_all_coordinates'&weather_config=='main'],ext[outcome_id%in%ids&scenario=='reference_daily_lag_extension']),fill=TRUE)
 ll<-ll[window%in%c('lag0','lag1','lag2','lag3','lag4','lag01','lag02','lag03','lag04')];ll[,win:=factor(window,levels=c('lag0','lag1','lag2','lag3','lag4','lag01','lag02','lag03','lag04'))];ll[,outcome:=factor(G[outcome_id],levels=G[ids])];ll[,pol:=factor(P[as.character(pollutant)],levels=P)]
 p<-ggplot(ll,aes(win,OR))+geom_hline(yintercept=1,linetype=2,color='grey50')+geom_errorbar(aes(ymin=lower,ymax=upper),width=.15)+geom_point(color='#000000',size=1.6)+facet_grid(outcome~pol,scales='free_y')+labs(x='Exposure window',y='OR per 10 ug/m3 (95% CI)')+theme(axis.text.x=element_text(angle=45,hjust=1))
 saveplot(p,if(f=='two_group')'FigureS2a_daily_windows' else 'FigureS2b_subtype_daily_windows',9,if(f=='two_group')6 else 10)
 eq<-fread(file.path(O,'tables','supp_equal_knots_curves.csv'))[outcome_id%in%ids];eq[,model:='Equally spaced concentration knots'];cur[,model:='Percentile knots'];all<-rbindlist(list(cur,eq),fill=TRUE);all[,outcome:=factor(G[outcome_id],levels=G[ids])];all[,pol:=factor(P[as.character(pollutant)],levels=P)]
 p<-ggplot(all,aes(concentration,OR,linetype=model))+geom_hline(yintercept=1,linetype=2,color='grey50')+geom_line()+facet_grid(outcome~pol,scales='free')+labs(x='Lag 0-1 concentration (ug/m3)',y='OR relative to each model reference',linetype=NULL)+scale_linetype_manual(values=c('dashed','solid'))
 saveplot(p,if(f=='two_group')'FigureS7a_knots_sensitivity' else 'FigureS7b_subtype_knots_sensitivity',9,if(f=='two_group')6 else 10)
}
sc<-c(all_registry_all_coordinates='Full registry',strict_previous_adjudication='Strict event subset',core_addresses='Core addresses (unverified)',no_imputed_coordinates='No imputed coordinates',first_person_group_record='First record per person/group',anchored28_ICD3_scenario='Anchored 28-day scenario',trim_candidate_tails_0.1pct_complete_strata='Trim 0.1% exposure tails')
ext<-fread(file.path(O,'tables','supp_reference_extensions.csv'));r<-rbindlist(list(raw,ext),fill=TRUE)[outcome_id%in%c('CVD','CBVD')&window=='lag01'&weather_config=='main'&scenario%in%names(sc)]
for(g in c('CVD','CBVD')){z<-r[outcome_id==g];z[,scenario_label:=factor(sc[scenario],levels=rev(sc))];z[,pol:=factor(P[as.character(pollutant)],levels=P)];p<-ggplot(z,aes(OR,scenario_label))+geom_vline(xintercept=1,linetype=2,color='grey50')+geom_errorbar(aes(xmin=lower,xmax=upper),orientation='y',width=.15)+geom_point(color='#000000',size=2)+facet_grid(.~pol)+labs(x='OR per 10 ug/m3 (95% CI)',y=NULL,title=G[g]);saveplot(p,paste0('Figure6',if(g=='CVD')'a' else 'b','_quality_sensitivity'),10,4.5)}
t<-fread('outputs/air_pollution_cc/two_group/表1_两类疾病候选事件特征.csv');d<-melt(t,id.vars='疾病',measure.vars=c('年2023','年2024','年2025'),variable.name='year',value.name='events');d[,year:=gsub('年','',year)];d[,outcome:=ifelse(疾病=='心血管疾病','Cardiovascular','Cerebrovascular')]
p<-ggplot(d,aes(year,events))+geom_col(fill='#000000',width=.65)+geom_text(aes(label=format(events,big.mark=',')),vjust=-.3,size=4)+facet_wrap(~outcome,scales='free_y')+scale_y_continuous(expand=expansion(mult=c(0,.12)))+labs(x='Year',y='Reported candidate events (not incidence rate)');saveplot(p,'FigureS1_annual_counts',8,4)
# Calendar-flow counts describe the retained analytical candidates, not final eligible events.
screen<-fread('outputs/air_pollution_cc/candidate_flow.csv');raw_n<-sum(screen[step=='原始非空记录',n]);candidate_n<-sum(screen[step=='保留候选记录（非最终事件）',n]);s<-fread('outputs/air_pollution_cc/two_group/两类疾病关联与敏感性.csv')[scenario=='all_registry_all_coordinates'&weather_config=='main'&window=='lag01'];a<-fread('outputs/air_pollution_cc/two_group/两类疾病原始候选与审定状态.csv');cv<-sum(a[group=='CVD',n]);cb<-sum(a[group=='CBVD',n]);cve<-s[outcome_id=='CVD'&pollutant=='PM25',n_events][1];cbe<-s[outcome_id=='CBVD'&pollutant=='PM25',n_events][1]
flow<-data.table(x=c(5,5,2.5,7.5,2.5,7.5),y=c(9,7,4.5,4.5,2,2),label=c(paste('Raw nonempty records',raw_n,sep='\n'),paste('Preliminary candidate records',candidate_n,sep='\n'),paste('Cardiovascular candidates',cv,sep='\n'),paste('Cerebrovascular candidates',cb,sep='\n'),paste('Complete lag 0-1 strata',cve,'events',sep='\n'),paste('Complete lag 0-1 strata',cbe,'events',sep='\n')))
p<-ggplot(flow,aes(x,y,label=label))+geom_label(size=4.4,label.padding=unit(.35,'lines'),fill='#FFFFFF')+annotate('segment',x=c(5,5,5,2.5,7.5),xend=c(5,2.5,7.5,2.5,7.5),y=c(8.3,6.2,6.2,3.8,3.8),yend=c(7.7,5.3,5.3,2.7,2.7),arrow=arrow(length=unit(.15,'inches')))+annotate('text',x=5,y=.6,label='All estimates remain exploratory pending acute-event and spatial validation.',size=3.7)+xlim(0,10)+ylim(0,10)+theme_void();saveplot(p,'Figure1_candidate_flow',8,6.5)
cat('Figures complete\n')
